In [1]:
import gym
import os
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [2]:
env = gym.make('IntelligentPantry-v1')

In [3]:
episodes = 5 
for episode in range(1,episodes+1):
    state = env.reset()
    done = False
    score = 0
    
    while not done:
        #env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+= reward
    print("Episode:{} Score:{}".format(episode,score))
env.close()

Episode:1 Score:-103.29527667664873
Episode:2 Score:-97.28717464004029
Episode:3 Score:-113.70252853770218
Episode:4 Score:-102.16442395309222
Episode:5 Score:-103.36030515506343


In [4]:
env.action_space

Box(-1.0, 1.0, (2,), float32)

In [5]:
env.action_space.sample()

array([0.7725668, 0.3274617], dtype=float32)

In [6]:
env.observation_space

Box(-inf, inf, (11,), float64)

In [7]:
env.step(1)

(array([ 0.83478577, -0.97261645,  0.5505749 ,  0.2324161 , -0.08778584,
         0.0257037 ,  1.87623715,  3.87752434, -0.19554875, -0.23272672,
         0.        ]),
 -1.2989277012743594,
 True,
 {'reward_dist': -0.2989277012743593,
  'reward_ctrl': -1,
  'TimeLimit.truncated': True})

In [8]:
env.spec.reward_threshold

-3.75

In [6]:
a=[1,2,3,4,5,6]
a[:-2]

[1, 2, 3, 4]

In [9]:
import numpy as np
env.np_random.uniform(low=-0.1, high=0.1, size=env.model.nq)

array([-0.08364105, -0.04591886,  0.19119831, -0.05196949])

In [8]:
env.init_qpos

array([ 0. ,  0. ,  0.1, -0.1])

# Train

In [10]:
log_path = os.path.join('training','Logs')

In [11]:
log_path

'training/Logs'

In [12]:
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cuda device


In [13]:
model.learn(total_timesteps = 500000)

2021-11-01 19:02:18.071919: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/juan/Documents/Github/IntelligentPantry/Juan's project/PP/lib/python3.9/site-packages/mujoco_py/binaries/linux/mujoco210/bin
2021-11-01 19:02:18.071986: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Logging to training/Logs/PPO_5
-----------------------------
| time/              |      |
|    fps             | 623  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 716          |
|    iterations           | 2            |
|    time_elapsed         | 5            |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0026080823 |
|    clip_fraction        | 0            |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.81        |
|    explained_variance   | -25.4        |
|    learning_rate        | 0.0003       |
|    loss                 | 92.1         |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.00388     |
|    std                  | 0.98         |
|    value_loss           | 

In [29]:
 evaluate_policy(model,env,n_eval_episodes=20,render=False)

(-10.952795110977604, 1.381131565317606)

In [19]:
from stable_baselines3 import DDPG

env = gym.make("Reacher-v2")
n_actions = env.action_space.shape[-1]

In [20]:
model2 = DDPG('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [21]:
model2.learn(total_timesteps=500000, log_interval=10)

Logging to training/Logs/DDPG_1
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 50       |
|    ep_rew_mean     | -24.8    |
| time/              |          |
|    episodes        | 10       |
|    fps             | 299      |
|    time_elapsed    | 1        |
|    total timesteps | 500      |
| train/             |          |
|    actor_loss      | 0.847    |
|    critic_loss     | 0.0119   |
|    learning_rate   | 0.001    |
|    n_updates       | 350      |
---------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 50       |
|    ep_rew_mean     | -19.3    |
| time/              |          |
|    episodes        | 20       |
|    fps             | 269      |
|    time_elapsed    | 3        |
|    total timesteps | 1000     |
| train/             |          |
|    actor_loss      | 1.44     |
|    critic_loss     | 0.00309  |
|    learning_rate   | 0.001    |
|    n_updates  

In [30]:
 evaluate_policy(model2,env,n_eval_episodes=20,render=False)

(-5.774505365124059, 2.05174155786902)

In [23]:
from stable_baselines3 import TD3

In [34]:
model3 = TD3("MlpPolicy",env,verbose=1)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [35]:
model3.learn(total_timesteps=500000,log_interval=10)

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 50       |
|    ep_rew_mean     | -33.9    |
| time/              |          |
|    episodes        | 10       |
|    fps             | 243      |
|    time_elapsed    | 2        |
|    total timesteps | 500      |
| train/             |          |
|    actor_loss      | 1.19     |
|    critic_loss     | 0.0292   |
|    learning_rate   | 0.001    |
|    n_updates       | 350      |
---------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 50       |
|    ep_rew_mean     | -29.3    |
| time/              |          |
|    episodes        | 20       |
|    fps             | 216      |
|    time_elapsed    | 4        |
|    total timesteps | 1000     |
| train/             |          |
|    actor_loss      | 1.69     |
|    critic_loss     | 0.0248   |
|    learning_rate   | 0.001    |
|    n_updates       | 850      |
--------------

In [14]:
 evaluate_policy(model3,env,n_eval_episodes=20,render=False)

NameError: name 'model3' is not defined